console.log("hello")
console.log("hello")
console.log("database host=localhost ")
console.log("database user=yourusername ")
console.log("database password=yourpassword ")
console.log("database db=postgres ")
console.log("secrets=5432 ")
console.log("database database=yourdatabase ")