title = "Custom Gitleaks Config for Testing"

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
secretGroup = 0
tags = ["aws", "key"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws(.{0,20})?(?-i)['"][0-9a-zA-Z/+]{40}['"]'''
secretGroup = 0
tags = ["aws", "key"]

[[rules]]
id = "azure-storage-key"
description = "Azure Storage Account Key"
regex = '''[a-zA-Z0-9+/]{88}=='''
secretGroup = 0
tags = ["azure", "key"]

[[rules]]
id = "gcp-api-key"
description = "Google Cloud API Key"
regex = '''AIza[0-9A-Za-z\-_]{35}'''
secretGroup = 0
tags = ["gcp", "key"]

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[A-Za-z0-9_-]+?\.[A-Za-z0-9._-]+?\.[A-Za-z0-9._-]+'''
secretGroup = 0
tags = ["jwt", "token"]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api|secret|token|key)(.{0,20})?['"][0-9a-zA-Z-_]{16,45}['"]'''
secretGroup = 0
tags = ["generic", "key"]
