name: Gitleaks Secret Scan

on:
  pull_request:
    branches:
      - develop

jobs:
  gitleaks-scan:
    name: Run Gitleaks on PR changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Required to get full history for diff

      - name: Run Gitleaks on PR diff
        id: gitleaks
        run: |
          echo "🔎 Running Gitleaks on PR changes..."
          # Scan only the diff between PR head and base
          gitleaks detect \
            --source . \
            --report-path gitleaks-report.json \
            --exit-code 1 \
            --no-git \
            --log-level debug \
            --redact \
            --report-format json \
            --commit-from $(git merge-base origin/${{ github.base_ref }} HEAD) \
            --commit-to HEAD

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
