name: Gitleaks Secret Scan

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run Gitleaks with default rules
      - name: Run Gitleaks (Default Rules)
        id: gitleaks-default
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-path gitleaks-report.json --exit-code 1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        continue-on-error: false   # ❌ Fail immediately if secrets are found

      # Upload report as artifact
      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
