name: Gitleaks Secret Scan

on:
  pull_request:
    branches:
      - develop

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-path gitleaks-report.json --verbose --no-git
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        continue-on-error: true

      - name: Check Results
        run: |
          if [ -f gitleaks-report.json ]; then
            echo "Report contents:"
            cat gitleaks-report.json
            if [ -s gitleaks-report.json ]; then
              echo "🚨 Secrets found!"
              exit 1
            fi
          fi

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json