name: Gitleaks Secret Scan

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1️⃣ Run Gitleaks with default rules
      - name: Run Gitleaks (Default Rules)
        id: gitleaks-default
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-path gitleaks-default-report.json --exit-code 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Run Gitleaks with custom rules
      - name: Run Gitleaks (Custom Rules)
        id: gitleaks-custom
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --config-path .github/gitleaks/gitleaks.toml --source . --report-path gitleaks-custom-report.json --exit-code 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Upload both reports as artifacts
      - name: Upload Gitleaks Reports
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-reports
          path: |
            gitleaks-default-report.json
            gitleaks-custom-report.json
